In [ ]:
import pandas as pd

kaggle

*   train  ==> model training  tran,val,testing
*   test  --> model performance
*   submit



In [ ]:
# %cd '/content/drive/My Drive'

In [ ]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/train.csv')

In [ ]:
dataset.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [ ]:
dataset.dropna()

id  ... label
0          0  ...     1
1          1  ...     0
2          2  ...     1
3          3  ...     1
4          4  ...     1
...      ...  ...   ...
20795  20795  ...     0
20796  20796  ...     0
20797  20797  ...     0
20798  20798  ...     1
20799  20799  ...     1

[18285 rows x 5 columns]

In [ ]:
dataset = dataset.dropna()

In [ ]:
X = dataset.drop('label', axis = 1)

In [ ]:
y = dataset['label']

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.3.0'

In [ ]:
from tensorflow.keras.layers import Embedding

In [ ]:
voc_size = 5000

i don't know

n meaning i don't know
m meaning i don't know

voc_size = 5000 


dataset 50000 rows
50000 rows 
i am an actor
ma name is xx.
ma name is xx.
you can also call me as xx.

14 words





0 oov out of vocubalry
1 to 5000 
the 1
a 2 

an 0
articale 0


In [ ]:
msg = X.copy()

In [ ]:
msg.reset_index(inplace = True)

In [ ]:
msg.head()

index  ...                                               text
0      0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1      1  ...  Ever get the feeling your life circles the rou...
2      2  ...  Why the Truth Might Get You Fired October 29, ...
3      3  ...  Videos 15 Civilians Killed In Single US Airstr...
4      4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 5 columns]

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
ps.stem("feeling")

'feel'

In [ ]:
#Data preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(msg)):
  print(i)
  review = re.sub('[^a-zA-Z]', ' ', msg['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
13443
1

In [ ]:
mean square root
y =1
y^ =0.6
 
(y^ - y)2 = 0.4

0.4 error

w = [ 0, 0.3 , 0.8] = 1
 

0.4 

In [ ]:
dense

w *x +b

lstm = > w
x - > original

In [ ]:
import numpy as np
np.random.normal(size=40)

array([-0.29777641,  0.1057718 , -0.22001507,  1.29517214, -0.37627525,
        0.07198853, -0.75081949,  0.29298645,  1.85887811, -1.12247373,
        0.34039616, -0.50800661,  0.1257285 , -0.63080906, -1.0863124 ,
       -0.290736  , -0.27678295,  0.06644724, -0.55803965,  0.39243422,
       -0.07811868,  0.46980474,  1.36406552, -0.06975195,  0.90584813,
       -0.3650019 ,  1.55830394, -1.52361389,  0.37690411,  1.33675356,
        1.38584272,  0.34986542,  0.88401451, -0.89292268, -0.03575405,
       -0.96497935,  0.29965683, -0.09919836, -0.25158262, -2.20955579])

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
onehot_repr = [one_hot(words, voc_size)for words in corpus]
onehot_repr

[[4090, 1609, 2279, 699, 813, 459, 4138, 4122, 4266, 1633],
 [4393, 2891, 2780, 4380, 4735, 1629, 2282],
 [253, 2024, 3268, 4509],
 [1325, 2793, 3602, 55, 3865, 2304],
 [2204, 4735, 2132, 2957, 4716, 2161, 4735, 2415, 2944, 599],
 [3418,
  3828,
  2216,
  698,
  2412,
  2251,
  102,
  3065,
  649,
  2722,
  3288,
  3395,
  767,
  2034,
  2282],
 [1859, 4921, 3239, 4806, 3098, 4957, 1592, 4314, 3373, 626, 3652],
 [363, 4917, 2885, 4014, 3910, 2976, 2251, 1853, 3373, 626, 3652],
 [3143, 3155, 322, 3622, 2777, 4720, 3486, 3335, 2251, 3840],
 [4172, 1995, 3976, 3892, 2239, 2905, 2429, 3270],
 [802, 4841, 151, 4842, 757, 1309, 4163, 1764, 2090, 1103, 128],
 [55, 1986, 813, 4720, 2251, 3910],
 [1045, 725, 3695, 3616, 3002, 888, 4562, 483, 380],
 [1111, 4976, 1990, 1237, 4763, 1404, 3925, 3373, 626, 3652],
 [3544, 2924, 3601, 456, 573, 3373, 626, 3652],
 [4817, 2832, 4015, 2438, 728, 4929, 78, 4497, 238, 4946],
 [474, 3299, 2891],
 [2087, 1621, 1089, 881, 2251, 3412, 2630, 2282],
 [460, 3747,

In [ ]:
sent_length = 20
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0 ... 4122 4266 1633]
 [   0    0    0 ... 4735 1629 2282]
 [   0    0    0 ... 2024 3268 4509]
 ...
 [   0    0    0 ... 3373  626 3652]
 [   0    0    0 ... 3325 1232 4360]
 [   0    0    0 ... 4894 2604 4724]]


In [ ]:
len(embedded_docs)

18285

In [ ]:
##Creating Model

embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
len(embedded_docs), y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [ ]:
X_final.shape, y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.33, random_state = 42)

Model Training

In [ ]:
### Final Training

model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs = 10, batch_size = 64)

Epoch 1/10
192/192 [==============================] - 7s 35ms/step - loss: 0.3365 - accuracy: 0.8397 - val_loss: 0.1963 - val_accuracy: 0.9145
Epoch 2/10
192/192 [==============================] - 6s 32ms/step - loss: 0.1420 - accuracy: 0.9444 - val_loss: 0.2123 - val_accuracy: 0.9112
Epoch 3/10
192/192 [==============================] - 6s 32ms/step - loss: 0.1020 - accuracy: 0.9619 - val_loss: 0.2238 - val_accuracy: 0.9173
Epoch 4/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0746 - accuracy: 0.9729 - val_loss: 0.2546 - val_accuracy: 0.9138
Epoch 5/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0565 - accuracy: 0.9804 - val_loss: 0.2966 - val_accuracy: 0.9077
Epoch 6/10
192/192 [==============================] - 6s 33ms/step - loss: 0.0408 - accuracy: 0.9855 - val_loss: 0.3326 - val_accuracy: 0.9102
Epoch 7/10
192/192 [==============================] - 6s 32ms/step - loss: 0.0317 - accuracy: 0.9898 - val_loss: 0.4169 - val_accuracy: 0.9065

Performance Metrics and Accuracy

In [ ]:
y_pred = model.predict_classes(X_test)


Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[3121,  298],
       [ 284, 2332]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9035625517812759